apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "maintenance.fullname" . }}
  namespace: {{ include "maintenance.namespace" . }}
  labels:
    {{- include "maintenance.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "maintenance.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "maintenance.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/caddy
            - name: html
              mountPath: /usr/share/caddy
      volumes:
        - name: config
          configMap:
            name: {{ include "maintenance.fullname" . }}-caddy
        - name: html
          configMap:
            name: {{ include "maintenance.fullname" . }}-html
